server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/valle_del_sol
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update