

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/valle_del_sol
      JWT_SECRET: supersecret
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: valle_del_sol
    ports:
      - "5432:5432"
