
services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: mysql://root:password@db:3306/valledelsol
      JWT_SECRET: supersecret
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: valledelsol
    ports:
      - "3306:3306"