    steps:
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}       
        username: ubuntu                    
        key: ${{ secrets.EC2_SSH_KEY }}     
        port: 22
        script_stop: true                   
        script: |
          cd ~/caso_muni
          git reset --hard HEAD
          git pull origin branch6
          sudo docker-compose down
          sudo docker-compose up -d --build
          # El parámetro -T evita bloqueos por falta de terminal interactiva en GitHub Actions
          sudo docker-compose exec -T api_backend npx prisma db push
